on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 

      - name: "login to Docker"
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASS }}

      -name: "Bulding Docker imag"
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/myimage4 .

      -name: "Push to docker hup"
        run: docker push ${{ secrets.DOCKER_USERNAME }}/myimage4
